[package]
name = "att_verifier"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.0-nightly.20251016", directory="noir-projects/aztec-nr/aztec" }
business_program = { path = "../basic_business_program" }
string_search = { tag= "v0.3.3", git = "https://github.com/noir-lang/noir_string_search"}
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }