[package]
name = "basic_business_program"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.0-nightly.20251016", directory="noir-projects/aztec-nr/aztec" }