[package]
name = "otc_escrow"
type = "contract"
authors = ["Jack Gilcrest", "Harsh Bajpai"]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-nightly.20251016", directory = "noir-projects/aztec-nr/aztec" }
token_contract = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-nightly.20251016", directory = "noir-projects/noir-contracts/contracts/app/token_contract" }
att_verifier = { path = "../att_verifier" }
real_business_program = { path = "../real_business_program" }
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.1" }
